local LSM = LibStub("LibSharedMedia-3.0") 

LSM:Register("font", "Anton", [[Interface\Addons\LSM-GoogleFonts\fonts\Anton-Regular.ttf]]) 
LSM:Register("font", "Audiowide", [[Interface\Addons\LSM-GoogleFonts\fonts\Audiowide-Regular.ttf]]) 
LSM:Register("font", "Exo2", [[Interface\Addons\LSM-GoogleFonts\fonts\Exo2-Regular.ttf]]) 
LSM:Register("font", "Geo", [[Interface\Addons\LSM-GoogleFonts\fonts\Geo-Regular.ttf]]) 
LSM:Register("font", "Monda", [[Interface\Addons\LSM-GoogleFonts\fonts\Monda-Regular.ttf]]) 
LSM:Register("font", "Nova Square", [[Interface\Addons\LSM-GoogleFonts\fonts\NovaSquare.ttf]]) 
LSM:Register("font", "Open Sans Condensed Bold", [[Interface\Addons\LSM-GoogleFonts\fonts\OpenSansCondensed-Bold.ttf]]) 
LSM:Register("font", "Orbitron", [[Interface\Addons\LSM-GoogleFonts\fonts\Orbitron-Regular.ttf]]) 
LSM:Register("font", "Quantico", [[Interface\Addons\LSM-GoogleFonts\fonts\Quantico-Regular.ttf]]) 
LSM:Register("font", "Roboto", [[Interface\Addons\LSM-GoogleFonts\fonts\Roboto-Regular.ttf]]) 
LSM:Register("font", "Teko", [[Interface\Addons\LSM-GoogleFonts\fonts\Teko-Regular.ttf]]) 
LSM:Register("font", "Titillium Web", [[Interface\Addons\LSM-GoogleFonts\fonts\TitilliumWeb-Regular.ttf]]) 
LSM:Register("font", "Ubuntu", [[Interface\Addons\LSM-GoogleFonts\fonts\Ubuntu-Regular.ttf]]) 
LSM:Register("font", "VT323", [[Interface\Addons\LSM-GoogleFonts\fonts\VT323-Regular.ttf]]) 
